<?php

/**
 * Implements hook_menu_alter().
 */
function field_settings_menu_alter(&$items) {
  // There's no easy way to alter the table on this page... so, we'll override
  // it and add our own columns.
  $items['admin/reports/fields']['file'] = 'field_settings.admin.inc';
  $items['admin/reports/fields']['page callback'] = 'field_settings_fields_list';
  $items['admin/reports/fields']['module'] = 'field_settings';
}

/**
 * Implements hook_menu().
 */
function field_settings_menu() {
  $items = array();

  $items['admin/reports/fields/%'] = array(
    'title' => 'Field Details',
    'description' => 'Details for a particular field.',
    'page callback' => 'field_settings_field_details',
    'page arguments' => array(3),
    'access arguments' => array('administer content types'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'field_settings.admin.inc',
  );
  $items['admin/reports/fields/%/view'] = array(
    'title' => 'Field Details',
    'weight' => -10,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/reports/fields/%/edit'] = array(
    'title' => 'Edit Field',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('field_settings_field_edit_form', 3),
    'access arguments' => array('administer content types'),
    'type' => MENU_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * Field Edit form
 */
function field_settings_field_edit_form($form, &$form_state, $field_name) {
  // Get field info
  $field = field_info_field($field_name);

  // Build the form based on the field info
  $form['field_settings'] = field_settings_render_field_info($field, TRUE);

  // Set the tree to true.
  $form['field_settings']['#tree'] = TRUE;

  // Set the acitons
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array('#type' => 'submit', '#value' => t('Save'));

  return $form;
}

/**
 * Submit handler
 */
function field_settings_field_edit_form_submit($form, &$form_state) {
  // Get the field settings from the form_state
  $field = $form_state['values']['field_settings'];
  
  // Update the field and hope that nothing goes wrong
  field_update_field($field);
}

/**
 * Helper function to build the form from the field_info array
 *
 * @param $array
 *   Array - An array... which will be broken down into textfields, unless
 *   we encounter an array... in which case, we recurse.
 *
 * @param $form_items
 *   Bool - Should we return textfield form items?
 *
 * @return We return a FAPI formatted array consisting of textfields and fieldsets
 */
function field_settings_render_field_info($array, $form_items = FALSE) {
  $form = array();

  foreach ($array as $key => $val) {
    // If we have an empty array, we don't want to get rid of it.
    if (is_array($val) && empty($val)) {
      $form[$key] = array(
        '#type' => 'value',
        '#value' => array(),
      );
    }
    // If we have an empty array, we don't want to get rid of it.
    else if (is_array($val) && !empty($val)) {
      $form[$key] = array(
        '#type' => 'fieldset',
        '#title' => $key.' = array()',
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      ) + field_settings_render_field_info($val, $form_items);
    }
    // Or, render the value.
    else if ($form_items) {
      $form[$key] = array(
        '#type' => 'textfield',
        '#field_prefix' => $key.' = ',
        '#default_value' => $val,
      );
    }
    // Or, just render a textfield.
    else {
      $form[$key] = array(
        '#type' => 'item',
        '#title' => $key.' = '.$val,
      );
    }
  }

  return $form;  
}